<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BaiVietSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $baiviets = [
            [
                'tieu_de' => 'Bài viết 1',
                'slug' => 'bai-viet-1',
                'hinh_anh' => 'a1.jpg',
                'tom_tat' => 'Tóm tắt bài viết 1',
                'noi_dung' => 'Nội dung chi tiết bài viết 1',
                'loai' => 'tin-tuc',
                'ngay_phat_hanh' => '2025-11-01',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => false,
                'is_promo' => false,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 1',
                'dien_vien' => 'Diễn viên A, Diễn viên B',
                'ngon_ngu' => 'Tiếng Việt',
                'dinh_dang' => '2D',
                'phu_de' => 'Không',
                'gioi_han_tuoi' => 'P',
                'thoi_luong' => 120,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tieu_de' => 'Bài viết 2',
                'slug' => 'bai-viet-2',
                'hinh_anh' => 'a2.jpg',
                'tom_tat' => 'Tóm tắt bài viết 2',
                'noi_dung' => 'Nội dung chi tiết bài viết 2',
                'loai' => 'khuyen-mai',
                'ngay_phat_hanh' => '2025-11-02',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => false,
                'is_promo' => true,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 2',
                'dien_vien' => 'Diễn viên C, Diễn viên D',
                'ngon_ngu' => 'Tiếng Anh',
                'dinh_dang' => '2D',
                'phu_de' => 'Có',
                'gioi_han_tuoi' => 'P',
                'thoi_luong' => 110,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tieu_de' => 'Bài viết 3',
                'slug' => 'bai-viet-3',
                'hinh_anh' => 'a3.jpg',
                'tom_tat' => 'Tóm tắt bài viết 3',
                'noi_dung' => 'Nội dung chi tiết bài viết 3',
                'loai' => 'tin-tuc',
                'ngay_phat_hanh' => '2025-11-03',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => true,
                'is_promo' => false,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 3',
                'dien_vien' => 'Diễn viên E, Diễn viên F',
                'ngon_ngu' => 'Tiếng Pháp',
                'dinh_dang' => '3D',
                'phu_de' => 'Không',
                'gioi_han_tuoi' => 'C13',
                'thoi_luong' => 100,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tieu_de' => 'Bài viết 4',
                'slug' => 'bai-viet-4',
                'hinh_anh' => 'a4.jpg',
                'tom_tat' => 'Tóm tắt bài viết 4',
                'noi_dung' => 'Nội dung chi tiết bài viết 4',
                'loai' => 'khuyen-mai',
                'ngay_phat_hanh' => '2025-11-04',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => false,
                'is_promo' => true,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 4',
                'dien_vien' => 'Diễn viên G, Diễn viên H',
                'ngon_ngu' => 'Tiếng Việt',
                'dinh_dang' => '2D',
                'phu_de' => 'Không',
                'gioi_han_tuoi' => 'P',
                'thoi_luong' => 125,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tieu_de' => 'Bài viết 5',
                'slug' => 'bai-viet-5',
                'hinh_anh' => 'a5.jpg',
                'tom_tat' => 'Tóm tắt bài viết 5',
                'noi_dung' => 'Nội dung chi tiết bài viết 5',
                'loai' => 'tin-tuc',
                'ngay_phat_hanh' => '2025-11-05',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => true,
                'is_promo' => false,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 5',
                'dien_vien' => 'Diễn viên I, Diễn viên J',
                'ngon_ngu' => 'Tiếng Anh',
                'dinh_dang' => '2D',
                'phu_de' => 'Có',
                'gioi_han_tuoi' => 'P',
                'thoi_luong' => 95,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tieu_de' => 'Bài viết 6',
                'slug' => 'bai-viet-6',
                'hinh_anh' => 'a6.jpg',
                'tom_tat' => 'Tóm tắt bài viết 6',
                'noi_dung' => 'Nội dung chi tiết bài viết 6',
                'loai' => 'khuyen-mai',
                'ngay_phat_hanh' => '2025-11-06',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => false,
                'is_promo' => true,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 6',
                'dien_vien' => 'Diễn viên K, Diễn viên L',
                'ngon_ngu' => 'Tiếng Pháp',
                'dinh_dang' => '3D',
                'phu_de' => 'Không',
                'gioi_han_tuoi' => 'C13',
                'thoi_luong' => 105,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Thêm 3 bài viết nữa không cần ảnh a7-a9 nếu muốn
            [
                'tieu_de' => 'Bài viết 7',
                'slug' => 'bai-viet-7',
                'hinh_anh' => 'a1.jpg',
                'tom_tat' => 'Tóm tắt bài viết 7',
                'noi_dung' => 'Nội dung chi tiết bài viết 7',
                'loai' => 'tin-tuc',
                'ngay_phat_hanh' => '2025-11-07',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => false,
                'is_promo' => false,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 7',
                'dien_vien' => 'Diễn viên M, Diễn viên N',
                'ngon_ngu' => 'Tiếng Việt',
                'dinh_dang' => '2D',
                'phu_de' => 'Không',
                'gioi_han_tuoi' => 'P',
                'thoi_luong' => 115,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tieu_de' => 'Bài viết 8',
                'slug' => 'bai-viet-8',
                'hinh_anh' => 'a2.jpg',
                'tom_tat' => 'Tóm tắt bài viết 8',
                'noi_dung' => 'Nội dung chi tiết bài viết 8',
                'loai' => 'khuyen-mai',
                'ngay_phat_hanh' => '2025-11-08',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => false,
                'is_promo' => true,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 8',
                'dien_vien' => 'Diễn viên O, Diễn viên P',
                'ngon_ngu' => 'Tiếng Anh',
                'dinh_dang' => '2D',
                'phu_de' => 'Có',
                'gioi_han_tuoi' => 'P',
                'thoi_luong' => 100,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tieu_de' => 'Bài viết 9',
                'slug' => 'bai-viet-9',
                'hinh_anh' => 'a3.jpg',
                'tom_tat' => 'Tóm tắt bài viết 9',
                'noi_dung' => 'Nội dung chi tiết bài viết 9',
                'loai' => 'tin-tuc',
                'ngay_phat_hanh' => '2025-11-09',
                'ngay_ket_thuc' => '2025-11-30',
                'is_active' => true,
                'is_featured' => true,
                'is_promo' => false,
                'views' => 0,
                'dao_dien' => 'Đạo diễn 9',
                'dien_vien' => 'Diễn viên Q, Diễn viên R',
                'ngon_ngu' => 'Tiếng Pháp',
                'dinh_dang' => '3D',
                'phu_de' => 'Không',
                'gioi_han_tuoi' => 'C13',
                'thoi_luong' => 130,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('baiviets')->insert($baiviets);
    }
}
